/***************** USER REGISTER **************** */
export const USER_REGISTER = "USER_REGISTER";
export const USER_REGISTER_FAILED = "USER_REGISTER_FAILED";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
/***************** USER REGISTER **************** */
/***************** USER REGISTER **************** */
export const USER_LOGIN = "USER_LOGIN";
export const GET_AUTH_USER = "USER_REGISTER";
export const USER_LOADING = "USER_LOADING";
export const LOGOUT = "LOGOUT";
export const AUTH_ERRORS = "AUTH_ERRORS";
